### ISSUE TITLE
Fix default example

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/vmext-demo#13]
the visualization of the standard example for the comparision method _identical_ is wrong. The bound variable _t_ from the left integral is missing.

**Comment by vstange** [comment]
Should be moved to the vmext project, since this is an error inside the merged ast?

**Comment by vstange** [comment]
Moved to https://github.com/ag-gipp/vmext/issues/13

**Comment by physikerwelt** [comment]
reopening. cf. ag-gipp/vmext#13

**Comment by vstange** [comment]
Hm. So I should exclude matches as a workaround?

**Comment by physikerwelt** [comment]
I would not see that as a workaround. If not all child elements did match, why should the partent match?

**Comment by vstange** [comment]
You are right. In this case we are talking about identical matches and another partial match could be discarded. But my question was a bit off, since I also wanted to ask if I should exclude any duplicate nodes found in matches of lower subtrees.

Example: `x^2+x` and `t^2+x`
I have two matches for `x` between these formulas. I need to sort one out since it can't be rendered otherwise.

**Comment by physikerwelt** [comment]
Ok that's something else. Please create a minimal example like 'a+a' vs 'a' and submit an enhancement bug to the vmext repo please.

**Comment by vstange** [comment]
An issue was opened: https://github.com/ag-gipp/vmext/issues/17

For the upcoming time any duplicate nodes found in matches of other subtrees are excluded. As a result our default example works fine now:

![auswahl_002](https://cloud.githubusercontent.com/assets/26301768/25219845/b72f3158-25ea-11e7-898f-9293a02423a1.png)
