### ISSUE TITLE
mathoid entry should return appropriate http access codes

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/vmext-demo#16]
https://github.com/ag-gipp/vmext-demo/blob/e82c659b0a84bda3b4198039ca5a59aa3ed4d1ee/src/main/java/org/citeplag/MathController.java#L101-L108 `--> 503?`
https://github.com/ag-gipp/vmext-demo/blob/e82c659b0a84bda3b4198039ca5a59aa3ed4d1ee/src/main/java/org/citeplag/MathController.java#L109-L111 `--> 500?`
@vstange what do you think and which [method](http://www.baeldung.com/spring-mvc-controller-custom-http-status-code) would you use?

**Comment by vstange** [comment]
@physikerwelt 
ResourceAccessException -> 503 is okay, or 400 bad request, since the mathoid url in this case is a parameter.

Exception -> maybe we should build an inner catch to distinguish and speficy whether it is a mathoid server error (then i think 502 bad gateway is correct) or really an internal error (with 500)
